In [1]:
import numpy as np
import pandas as pd

In [4]:
train=pd.read_csv('/content/train.csv')
test=pd.read_csv('/content/test.csv')
sample=pd.read_csv('/content/sample_submission.csv')

In [ ]:
train.tail(1)

,id,sudden_fever,headache,mouth_bleed,nose_bleed,muscle_pain,joint_pain,vomiting,rash,diarrhea,...,breathing_restriction,toe_inflammation,finger_inflammation,lips_irritation,itchiness,ulcers,toenail_loss,speech_problem,bullseye_rash,prognosis
706,706,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,Tungiasis

In [6]:
train['prognosis'].tail()

702       Plague
703      Malaria
704         Zika
705       Plague
706    Tungiasis
Name: prognosis, dtype: object

In [5]:
sample.tail()

       id                          prognosis
298  1005  Dengue Zika Japanese_encephalitis
299  1006  Dengue Zika Japanese_encephalitis
300  1007  Dengue Zika Japanese_encephalitis
301  1008  Dengue Zika Japanese_encephalitis
302  1009  Dengue Zika Japanese_encephalitis

In [ ]:
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from lightgbm import LGBMClassifier

x=train.drop(['id','prognosis'],axis=1)
mx=test.drop(['id'],axis=1)

y=train['prognosis']

lab=LabelEncoder()
y=lab.fit_transform(y)

xgc=XGBClassifier()
xgc.fit(x,y)
pro2= xgc.predict(mx)

dmc=RandomForestClassifier(random_state=40)
dmc.fit(x,y)
pro1=dmc.predict(mx)

rfc=DecisionTreeClassifier(random_state=40,max_depth=1)
rfc.fit(x,y)
pro3=rfc.predict(mx)

In [ ]:
a1 = pd.DataFrame()

pro1=lab.inverse_transform(pro1)
pro2=lab.inverse_transform(pro2)
pro3=lab.inverse_transform(pro3)

a1['prognosis_1']=pro1
a1['prognosis_2']=pro2
a1['prognosis_3']=pro3

a1['prognosis'] = a1.apply(lambda x: x['prognosis_1'] + "    " + x['prognosis_2'] + "    " + x['prognosis_3'], axis=1)

In [ ]:
a1.tail(-9)

,prognosis_1,prognosis_2,prognosis_3,prognosis
9,Yellow_Fever,Malaria,Japanese_encephalitis,Yellow_Fever Malaria Japanese_encephalitis
10,West_Nile_fever,Tungiasis,Japanese_encephalitis,West_Nile_fever Tungiasis Japanese_encep...
11,Rift_Valley_fever,Rift_Valley_fever,Japanese_encephalitis,Rift_Valley_fever Rift_Valley_fever Japa...
12,Rift_Valley_fever,Rift_Valley_fever,Japanese_encephalitis,Rift_Valley_fever Rift_Valley_fever Japa...
13,Chikungunya,Chikungunya,Japanese_encephalitis,Chikungunya Chikungunya Japanese_encepha...
...,...,...,...,...
298,Yellow_Fever,Yellow_Fever,Japanese_encephalitis,Yellow_Fever Yellow_Fever Japanese_encep...
299,Lyme_disease,Malaria,Japanese_encephalitis,Lyme_disease Malaria Japanese_encephalitis
300,West_Nile_fever,West_Nile_fever,Japanese_encephalitis,West_Nile_fever West_Nile_fever Japanese...
301,West_Nile_fever,Zika,Japanese_encephalitis,West_Nile_fever Zika Japanese_encephalitis
302,West_Nile_fever,Zika,Japanese_encephalitis,West_Nile_fever Zika Japanese_encephalitis